version: '3'

services:
  neo4j: 
    ports:
      - "7474:7474"
      - "7687:7687"

  minio:
    ports:
      - "9000:9000"

  mongo:
    ports:
      - "27017:27017"

  redis:
    ports:
      - "6379:6379"

  authserver:
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: Dockerfile
    command: ["python3", "main.py"] 
    ports:
      - "5000:5000"

  frontend:
    build:
      dockerfile: Dockerfile-Dev
    ports:
      - "4200:4200"